// Generated by scripts/gen-db-types.mjs from supabase/migrations. Do not edit by hand.
// Regenerate with: pnpm db:types (local) or pnpm db:types:remote (linked Supabase project).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "13" }
  public: {
    Tables: {
      ad_account_members: {
        Row: {
          ad_account_id: string
          company_id: string
          created_at: string
        }
        Insert: {
          ad_account_id: string
          company_id: string
          created_at?: string
        }
        Update: {
          ad_account_id?: string
          company_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_account_members_ad_account_id_fkey"
            columns: ["ad_account_id"]
            isOneToOne: false
            referencedRelation: "ad_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_account_members_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_accounts: {
        Row: {
          access_token_id: string | null
          act_id: string
          ads_client_id: string | null
          app_id: string
          app_secret_id: string | null
          archived_at: string | null
          backfilled_from: string | null
          company_id: string
          created_at: string
          created_by: string | null
          currency: string | null
          id: string
          kind: string
          last_checked_at: string | null
          last_error: string | null
          last_synced_at: string | null
          name: string | null
          next_sync_after: string | null
          status: string
          sync_paused: boolean
          synced_through: string | null
          timezone: string | null
          updated_at: string
        }
        Insert: {
          access_token_id?: string | null
          act_id: string
          ads_client_id?: string | null
          app_id: string
          app_secret_id?: string | null
          archived_at?: string | null
          backfilled_from?: string | null
          company_id: string
          created_at?: string
          created_by?: string | null
          currency?: string | null
          id?: string
          kind: string
          last_checked_at?: string | null
          last_error?: string | null
          last_synced_at?: string | null
          name?: string | null
          next_sync_after?: string | null
          status?: string
          sync_paused?: boolean
          synced_through?: string | null
          timezone?: string | null
          updated_at?: string
        }
        Update: {
          access_token_id?: string | null
          act_id?: string
          ads_client_id?: string | null
          app_id?: string
          app_secret_id?: string | null
          archived_at?: string | null
          backfilled_from?: string | null
          company_id?: string
          created_at?: string
          created_by?: string | null
          currency?: string | null
          id?: string
          kind?: string
          last_checked_at?: string | null
          last_error?: string | null
          last_synced_at?: string | null
          name?: string | null
          next_sync_after?: string | null
          status?: string
          sync_paused?: boolean
          synced_through?: string | null
          timezone?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_accounts_ads_client_id_fkey"
            columns: ["ads_client_id"]
            isOneToOne: true
            referencedRelation: "ads_clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_accounts_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: true
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_accounts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_ad_daily: {
        Row: {
          ad_account_id: string
          ad_id: string
          campaign_id: string
          clicks: number
          conversion_value: number
          conversions: number
          date: string
          impressions: number
          leads: number
          link_clicks: number
          reach: number
          spend: number
        }
        Insert: {
          ad_account_id: string
          ad_id: string
          campaign_id: string
          clicks?: number
          conversion_value?: number
          conversions?: number
          date: string
          impressions?: number
          leads?: number
          link_clicks?: number
          reach?: number
          spend?: number
        }
        Update: {
          ad_account_id?: string
          ad_id?: string
          campaign_id?: string
          clicks?: number
          conversion_value?: number
          conversions?: number
          date?: string
          impressions?: number
          leads?: number
          link_clicks?: number
          reach?: number
          spend?: number
        }
        Relationships: [
          {
            foreignKeyName: "ad_ad_daily_ad_account_id_fkey"
            columns: ["ad_account_id"]
            isOneToOne: false
            referencedRelation: "ad_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_ad_daily_ad_id_fkey"
            columns: ["ad_id"]
            isOneToOne: false
            referencedRelation: "ad_ads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_ad_daily_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "ad_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_ad_monthly: {
        Row: {
          ad_account_id: string
          ad_id: string
          campaign_id: string
          clicks: number
          conversion_value: number
          conversions: number
          impressions: number
          leads: number
          link_clicks: number
          month: string
          reach: number
          spend: number
        }
        Insert: {
          ad_account_id: string
          ad_id: string
          campaign_id: string
          clicks?: number
          conversion_value?: number
          conversions?: number
          impressions?: number
          leads?: number
          link_clicks?: number
          month: string
          reach?: number
          spend?: number
        }
        Update: {
          ad_account_id?: string
          ad_id?: string
          campaign_id?: string
          clicks?: number
          conversion_value?: number
          conversions?: number
          impressions?: number
          leads?: number
          link_clicks?: number
          month?: string
          reach?: number
          spend?: number
        }
        Relationships: [
          {
            foreignKeyName: "ad_ad_monthly_ad_account_id_fkey"
            columns: ["ad_account_id"]
            isOneToOne: false
            referencedRelation: "ad_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_ad_monthly_ad_id_fkey"
            columns: ["ad_id"]
            isOneToOne: false
            referencedRelation: "ad_ads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_ad_monthly_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "ad_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_ads: {
        Row: {
          ad_account_id: string
          campaign_id: string
          created_time: string | null
          effective_status: string | null
          first_seen_at: string
          id: string
          meta_id: string
          name: string
          preview_url: string | null
          status: string | null
          thumbnail_url: string | null
          updated_at: string
          updated_time: string | null
        }
        Insert: {
          ad_account_id: string
          campaign_id: string
          created_time?: string | null
          effective_status?: string | null
          first_seen_at?: string
          id?: string
          meta_id: string
          name: string
          preview_url?: string | null
          status?: string | null
          thumbnail_url?: string | null
          updated_at?: string
          updated_time?: string | null
        }
        Update: {
          ad_account_id?: string
          campaign_id?: string
          created_time?: string | null
          effective_status?: string | null
          first_seen_at?: string
          id?: string
          meta_id?: string
          name?: string
          preview_url?: string | null
          status?: string | null
          thumbnail_url?: string | null
          updated_at?: string
          updated_time?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ad_ads_ad_account_id_fkey"
            columns: ["ad_account_id"]
            isOneToOne: false
            referencedRelation: "ad_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_ads_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "ad_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_campaign_daily: {
        Row: {
          actions: Json | null
          ad_account_id: string
          campaign_id: string
          clicks: number
          conversion_value: number
          conversions: number
          date: string
          impressions: number
          leads: number
          link_clicks: number
          reach: number
          spend: number
          updated_at: string
        }
        Insert: {
          actions?: Json | null
          ad_account_id: string
          campaign_id: string
          clicks?: number
          conversion_value?: number
          conversions?: number
          date: string
          impressions?: number
          leads?: number
          link_clicks?: number
          reach?: number
          spend?: number
          updated_at?: string
        }
        Update: {
          actions?: Json | null
          ad_account_id?: string
          campaign_id?: string
          clicks?: number
          conversion_value?: number
          conversions?: number
          date?: string
          impressions?: number
          leads?: number
          link_clicks?: number
          reach?: number
          spend?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_campaign_daily_ad_account_id_fkey"
            columns: ["ad_account_id"]
            isOneToOne: false
            referencedRelation: "ad_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_campaign_daily_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "ad_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_campaigns: {
        Row: {
          ad_account_id: string
          category_id: string | null
          created_time: string | null
          daily_budget: number | null
          effective_status: string | null
          first_seen_at: string
          id: string
          lifetime_budget: number | null
          meta_id: string
          name: string
          objective: string | null
          start_time: string | null
          status: string | null
          stop_time: string | null
          updated_at: string
        }
        Insert: {
          ad_account_id: string
          category_id?: string | null
          created_time?: string | null
          daily_budget?: number | null
          effective_status?: string | null
          first_seen_at?: string
          id?: string
          lifetime_budget?: number | null
          meta_id: string
          name: string
          objective?: string | null
          start_time?: string | null
          status?: string | null
          stop_time?: string | null
          updated_at?: string
        }
        Update: {
          ad_account_id?: string
          category_id?: string | null
          created_time?: string | null
          daily_budget?: number | null
          effective_status?: string | null
          first_seen_at?: string
          id?: string
          lifetime_budget?: number | null
          meta_id?: string
          name?: string
          objective?: string | null
          start_time?: string | null
          status?: string | null
          stop_time?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ad_campaigns_ad_account_id_fkey"
            columns: ["ad_account_id"]
            isOneToOne: false
            referencedRelation: "ad_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_campaigns_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "ad_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_categories: {
        Row: {
          ad_account_id: string
          archived_at: string | null
          company_id: string | null
          created_at: string
          id: string
          match_text: string | null
          name: string
          normalized_name: string | null
        }
        Insert: {
          ad_account_id: string
          archived_at?: string | null
          company_id?: string | null
          created_at?: string
          id?: string
          match_text?: string | null
          name: string
          normalized_name?: never
        }
        Update: {
          ad_account_id?: string
          archived_at?: string | null
          company_id?: string | null
          created_at?: string
          id?: string
          match_text?: string | null
          name?: string
          normalized_name?: never
        }
        Relationships: [
          {
            foreignKeyName: "ad_categories_ad_account_id_fkey"
            columns: ["ad_account_id"]
            isOneToOne: false
            referencedRelation: "ad_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_categories_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      ad_reach_monthly: {
        Row: {
          ad_account_id: string
          campaign_id: string | null
          month: string
          reach: number
        }
        Insert: {
          ad_account_id: string
          campaign_id?: string | null
          month: string
          reach?: number
        }
        Update: {
          ad_account_id?: string
          campaign_id?: string | null
          month?: string
          reach?: number
        }
        Relationships: [
          {
            foreignKeyName: "ad_reach_monthly_ad_account_id_fkey"
            columns: ["ad_account_id"]
            isOneToOne: false
            referencedRelation: "ad_accounts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ad_reach_monthly_campaign_id_fkey"
            columns: ["campaign_id"]
            isOneToOne: false
            referencedRelation: "ad_campaigns"
            referencedColumns: ["id"]
          },
        ]
      }
      admin_audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          meta: Json
          target_user_id: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          meta?: Json
          target_user_id?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          meta?: Json
          target_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "admin_audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_audit_log_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      ads_clients: {
        Row: {
          business: string | null
          closed_at: string | null
          company_id: string
          created_at: string
          created_by: string | null
          email: string | null
          id: string
          lead_id: string | null
          name: string
          notes: string | null
          phone: string | null
          started_at: string
          status: string
          updated_at: string
        }
        Insert: {
          business?: string | null
          closed_at?: string | null
          company_id: string
          created_at?: string
          created_by?: string | null
          email?: string | null
          id?: string
          lead_id?: string | null
          name: string
          notes?: string | null
          phone?: string | null
          started_at?: string
          status?: string
          updated_at?: string
        }
        Update: {
          business?: string | null
          closed_at?: string | null
          company_id?: string
          created_at?: string
          created_by?: string | null
          email?: string | null
          id?: string
          lead_id?: string | null
          name?: string
          notes?: string | null
          phone?: string | null
          started_at?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "ads_clients_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ads_clients_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ads_clients_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: true
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      ads_manager_companies: {
        Row: {
          company_id: string
          created_at: string
          user_id: string
        }
        Insert: {
          company_id: string
          created_at?: string
          user_id: string
        }
        Update: {
          company_id?: string
          created_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ads_manager_companies_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ads_manager_companies_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      capital_entries: {
        Row: {
          amount: number
          archived_at: string | null
          archived_by: string | null
          company_id: string
          contributor: string
          created_at: string
          created_by: string
          description: string | null
          entry_date: string
          id: string
          item: string | null
          payment_mode: string | null
          quantity: number | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          amount: number
          archived_at?: string | null
          archived_by?: string | null
          company_id?: string
          contributor: string
          created_at?: string
          created_by: string
          description?: string | null
          entry_date: string
          id?: string
          item?: string | null
          payment_mode?: string | null
          quantity?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          amount?: number
          archived_at?: string | null
          archived_by?: string | null
          company_id?: string
          contributor?: string
          created_at?: string
          created_by?: string
          description?: string | null
          entry_date?: string
          id?: string
          item?: string | null
          payment_mode?: string | null
          quantity?: number | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "capital_entries_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "capital_entries_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "capital_entries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "capital_entries_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          archived_at: string | null
          brand_highlight: string | null
          created_at: string
          created_by: string | null
          finance_can_edit: boolean
          finance_group_id: string
          id: string
          logo_path: string | null
          name: string
          normalized_name: string | null
          updated_at: string
          won_to_ads_client: boolean
        }
        Insert: {
          archived_at?: string | null
          brand_highlight?: string | null
          created_at?: string
          created_by?: string | null
          finance_can_edit?: boolean
          finance_group_id: string
          id?: string
          logo_path?: string | null
          name: string
          normalized_name?: never
          updated_at?: string
          won_to_ads_client?: boolean
        }
        Update: {
          archived_at?: string | null
          brand_highlight?: string | null
          created_at?: string
          created_by?: string | null
          finance_can_edit?: boolean
          finance_group_id?: string
          id?: string
          logo_path?: string | null
          name?: string
          normalized_name?: never
          updated_at?: string
          won_to_ads_client?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "companies_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "companies_finance_group_id_fkey"
            columns: ["finance_group_id"]
            isOneToOne: false
            referencedRelation: "finance_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      expense_categories: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          finance_group_id: string
          id: string
          name: string
          normalized_name: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          finance_group_id: string
          id?: string
          name: string
          normalized_name?: never
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          finance_group_id?: string
          id?: string
          name?: string
          normalized_name?: never
        }
        Relationships: [
          {
            foreignKeyName: "expense_categories_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expense_categories_finance_group_id_fkey"
            columns: ["finance_group_id"]
            isOneToOne: false
            referencedRelation: "finance_groups"
            referencedColumns: ["id"]
          },
        ]
      }
      expense_recurrences: {
        Row: {
          active: boolean
          amount: number
          category: string
          category_id: string
          company_id: string
          created_at: string
          created_by: string
          day_of_month: number
          description: string | null
          id: string
          item: string | null
          next_date: string
          payment_mode: string | null
          quantity: number | null
          updated_at: string
        }
        Insert: {
          active?: boolean
          amount: number
          category?: string
          category_id: string
          company_id?: string
          created_at?: string
          created_by: string
          day_of_month: number
          description?: string | null
          id?: string
          item?: string | null
          next_date: string
          payment_mode?: string | null
          quantity?: number | null
          updated_at?: string
        }
        Update: {
          active?: boolean
          amount?: number
          category?: string
          category_id?: string
          company_id?: string
          created_at?: string
          created_by?: string
          day_of_month?: number
          description?: string | null
          id?: string
          item?: string | null
          next_date?: string
          payment_mode?: string | null
          quantity?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "expense_recurrences_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "expense_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expense_recurrences_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expense_recurrences_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      expenses: {
        Row: {
          amount: number
          archived_at: string | null
          archived_by: string | null
          category: string
          category_id: string
          company_id: string
          created_at: string
          created_by: string
          description: string | null
          expense_date: string
          id: string
          item: string | null
          payment_mode: string | null
          quantity: number | null
          recurrence_id: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          amount: number
          archived_at?: string | null
          archived_by?: string | null
          category?: string
          category_id: string
          company_id?: string
          created_at?: string
          created_by: string
          description?: string | null
          expense_date: string
          id?: string
          item?: string | null
          payment_mode?: string | null
          quantity?: number | null
          recurrence_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          amount?: number
          archived_at?: string | null
          archived_by?: string | null
          category?: string
          category_id?: string
          company_id?: string
          created_at?: string
          created_by?: string
          description?: string | null
          expense_date?: string
          id?: string
          item?: string | null
          payment_mode?: string | null
          quantity?: number | null
          recurrence_id?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "expenses_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "expense_categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_recurrence_id_fkey"
            columns: ["recurrence_id"]
            isOneToOne: false
            referencedRelation: "expense_recurrences"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      finance_activities: {
        Row: {
          action: string
          actor_id: string | null
          changes: Json
          company_id: string
          created_at: string
          entity_id: string
          entity_type: string
          id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          changes?: Json
          company_id?: string
          created_at?: string
          entity_id: string
          entity_type: string
          id?: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          changes?: Json
          company_id?: string
          created_at?: string
          entity_id?: string
          entity_type?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "finance_activities_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "finance_activities_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      finance_groups: {
        Row: {
          created_at: string
          id: string
        }
        Insert: {
          created_at?: string
          id?: string
        }
        Update: {
          created_at?: string
          id?: string
        }
        Relationships: []
      }
      follow_up_nag_silences: {
        Row: {
          follow_up_id: string
          revision: number
          silenced_at: string
          user_id: string
        }
        Insert: {
          follow_up_id: string
          revision: number
          silenced_at?: string
          user_id: string
        }
        Update: {
          follow_up_id?: string
          revision?: number
          silenced_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follow_up_nag_silences_follow_up_id_fkey"
            columns: ["follow_up_id"]
            isOneToOne: false
            referencedRelation: "follow_ups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_up_nag_silences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      follow_up_stars: {
        Row: {
          created_at: string
          follow_up_id: string
          pinned_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          follow_up_id: string
          pinned_at?: string | null
          user_id?: string
        }
        Update: {
          created_at?: string
          follow_up_id?: string
          pinned_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follow_up_stars_follow_up_id_fkey"
            columns: ["follow_up_id"]
            isOneToOne: false
            referencedRelation: "follow_ups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_up_stars_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      follow_ups: {
        Row: {
          assignee_id: string
          cancelled_at: string | null
          completed_at: string | null
          completed_by: string | null
          created_at: string
          created_by: string
          due_at: string
          id: string
          lead_id: string
          outcome: string | null
          revision: number
          state: Database["public"]["Enums"]["follow_up_state"]
          task: string
          updated_at: string
        }
        Insert: {
          assignee_id: string
          cancelled_at?: string | null
          completed_at?: string | null
          completed_by?: string | null
          created_at?: string
          created_by: string
          due_at: string
          id?: string
          lead_id: string
          outcome?: string | null
          revision?: number
          state?: Database["public"]["Enums"]["follow_up_state"]
          task: string
          updated_at?: string
        }
        Update: {
          assignee_id?: string
          cancelled_at?: string | null
          completed_at?: string | null
          completed_by?: string | null
          created_at?: string
          created_by?: string
          due_at?: string
          id?: string
          lead_id?: string
          outcome?: string | null
          revision?: number
          state?: Database["public"]["Enums"]["follow_up_state"]
          task?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "follow_ups_assignee_id_fkey"
            columns: ["assignee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_ups_completed_by_fkey"
            columns: ["completed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_ups_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_ups_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_activities: {
        Row: {
          actor_id: string | null
          body: string | null
          created_at: string
          edited_at: string | null
          follow_up_id: string | null
          id: string
          lead_id: string
          meta: Json
          type: Database["public"]["Enums"]["lead_activity_type"]
        }
        Insert: {
          actor_id?: string | null
          body?: string | null
          created_at?: string
          edited_at?: string | null
          follow_up_id?: string | null
          id?: string
          lead_id: string
          meta?: Json
          type: Database["public"]["Enums"]["lead_activity_type"]
        }
        Update: {
          actor_id?: string | null
          body?: string | null
          created_at?: string
          edited_at?: string | null
          follow_up_id?: string | null
          id?: string
          lead_id?: string
          meta?: Json
          type?: Database["public"]["Enums"]["lead_activity_type"]
        }
        Relationships: [
          {
            foreignKeyName: "lead_activities_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_activities_follow_up_id_fkey"
            columns: ["follow_up_id"]
            isOneToOne: false
            referencedRelation: "follow_ups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_activities_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_share_files: {
        Row: {
          added_at: string
          added_by: string | null
          file_id: string
          position: number
          removed_at: string | null
          share_id: string
        }
        Insert: {
          added_at?: string
          added_by?: string | null
          file_id: string
          position: number
          removed_at?: string | null
          share_id: string
        }
        Update: {
          added_at?: string
          added_by?: string | null
          file_id?: string
          position?: number
          removed_at?: string | null
          share_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_share_files_added_by_fkey"
            columns: ["added_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_share_files_file_id_fkey"
            columns: ["file_id"]
            isOneToOne: false
            referencedRelation: "library_files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_share_files_share_id_fkey"
            columns: ["share_id"]
            isOneToOne: false
            referencedRelation: "lead_shares"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_shares: {
        Row: {
          created_at: string
          created_by: string
          expires_at: string | null
          id: string
          last_notified_on: string | null
          last_viewed_at: string | null
          lead_id: string
          revoked_at: string | null
          revoked_by: string | null
          token: string | null
          token_hash: string
          updated_at: string
          view_count: number
        }
        Insert: {
          created_at?: string
          created_by: string
          expires_at?: string | null
          id?: string
          last_notified_on?: string | null
          last_viewed_at?: string | null
          lead_id: string
          revoked_at?: string | null
          revoked_by?: string | null
          token?: string | null
          token_hash: string
          updated_at?: string
          view_count?: number
        }
        Update: {
          created_at?: string
          created_by?: string
          expires_at?: string | null
          id?: string
          last_notified_on?: string | null
          last_viewed_at?: string | null
          lead_id?: string
          revoked_at?: string | null
          revoked_by?: string | null
          token?: string | null
          token_hash?: string
          updated_at?: string
          view_count?: number
        }
        Relationships: [
          {
            foreignKeyName: "lead_shares_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_shares_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_shares_revoked_by_fkey"
            columns: ["revoked_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_stars: {
        Row: {
          created_at: string
          lead_id: string
          pinned_at: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          lead_id: string
          pinned_at?: string | null
          user_id?: string
        }
        Update: {
          created_at?: string
          lead_id?: string
          pinned_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_stars_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_stars_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          archived_at: string | null
          archived_by: string | null
          company_id: string
          created_at: string
          created_by: string
          email: string | null
          id: string
          name: string
          niche_id: string
          owner_id: string
          phone: string
          phone_normalized: string
          source: string
          source_meta: Json
          stage_id: string
          status: Database["public"]["Enums"]["lead_outcome"]
          updated_at: string
          version: number
        }
        Insert: {
          archived_at?: string | null
          archived_by?: string | null
          company_id?: string
          created_at?: string
          created_by: string
          email?: string | null
          id?: string
          name: string
          niche_id: string
          owner_id: string
          phone: string
          phone_normalized: string
          source?: string
          source_meta?: Json
          stage_id: string
          status?: Database["public"]["Enums"]["lead_outcome"]
          updated_at?: string
          version?: number
        }
        Update: {
          archived_at?: string | null
          archived_by?: string | null
          company_id?: string
          created_at?: string
          created_by?: string
          email?: string | null
          id?: string
          name?: string
          niche_id?: string
          owner_id?: string
          phone?: string
          phone_normalized?: string
          source?: string
          source_meta?: Json
          stage_id?: string
          status?: Database["public"]["Enums"]["lead_outcome"]
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "leads_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_niche_id_fkey"
            columns: ["niche_id"]
            isOneToOne: false
            referencedRelation: "niches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_stage_id_fkey"
            columns: ["stage_id"]
            isOneToOne: false
            referencedRelation: "pipeline_stages"
            referencedColumns: ["id"]
          },
        ]
      }
      library_files: {
        Row: {
          archived_at: string | null
          archived_by: string | null
          company_id: string
          created_at: string
          created_by: string
          folder_id: string
          id: string
          mime_type: string
          name: string
          normalized_name: string | null
          position: number
          size_bytes: number
          storage_path: string
          thumb_path: string | null
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          archived_by?: string | null
          company_id?: string
          created_at?: string
          created_by: string
          folder_id: string
          id?: string
          mime_type: string
          name: string
          normalized_name?: never
          position?: number
          size_bytes: number
          storage_path: string
          thumb_path?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          archived_by?: string | null
          company_id?: string
          created_at?: string
          created_by?: string
          folder_id?: string
          id?: string
          mime_type?: string
          name?: string
          normalized_name?: never
          position?: number
          size_bytes?: number
          storage_path?: string
          thumb_path?: string | null
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "library_files_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "library_files_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "library_files_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "library_files_folder_id_fkey"
            columns: ["folder_id"]
            isOneToOne: false
            referencedRelation: "library_folders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "library_files_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      library_folders: {
        Row: {
          archived_at: string | null
          archived_by: string | null
          company_id: string
          created_at: string
          created_by: string
          id: string
          name: string
          normalized_name: string | null
          parent_id: string | null
          position: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          archived_at?: string | null
          archived_by?: string | null
          company_id?: string
          created_at?: string
          created_by: string
          id?: string
          name: string
          normalized_name?: never
          parent_id?: string | null
          position?: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          archived_at?: string | null
          archived_by?: string | null
          company_id?: string
          created_at?: string
          created_by?: string
          id?: string
          name?: string
          normalized_name?: never
          parent_id?: string | null
          position?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "library_folders_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "library_folders_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "library_folders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "library_folders_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "library_folders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "library_folders_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      meta_integrations: {
        Row: {
          access_token_id: string
          app_id: string
          app_secret_id: string
          company_id: string
          created_at: string
          last_checked_at: string | null
          last_error: string | null
          last_event_at: string | null
          page_id: string
          page_name: string | null
          status: string
          updated_at: string
          verify_token: string
        }
        Insert: {
          access_token_id: string
          app_id: string
          app_secret_id: string
          company_id: string
          created_at?: string
          last_checked_at?: string | null
          last_error?: string | null
          last_event_at?: string | null
          page_id: string
          page_name?: string | null
          status?: string
          updated_at?: string
          verify_token?: string
        }
        Update: {
          access_token_id?: string
          app_id?: string
          app_secret_id?: string
          company_id?: string
          created_at?: string
          last_checked_at?: string | null
          last_error?: string | null
          last_event_at?: string | null
          page_id?: string
          page_name?: string | null
          status?: string
          updated_at?: string
          verify_token?: string
        }
        Relationships: [
          {
            foreignKeyName: "meta_integrations_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: true
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      meta_lead_events: {
        Row: {
          ad_id: string | null
          ad_name: string | null
          adset_id: string | null
          attempts: number
          campaign_id: string | null
          campaign_name: string | null
          company_id: string
          created_at: string
          error: string | null
          form_id: string | null
          form_name: string | null
          id: string
          lead_id: string | null
          leadgen_id: string
          state: string
          updated_at: string
        }
        Insert: {
          ad_id?: string | null
          ad_name?: string | null
          adset_id?: string | null
          attempts?: number
          campaign_id?: string | null
          campaign_name?: string | null
          company_id: string
          created_at?: string
          error?: string | null
          form_id?: string | null
          form_name?: string | null
          id?: string
          lead_id?: string | null
          leadgen_id: string
          state?: string
          updated_at?: string
        }
        Update: {
          ad_id?: string | null
          ad_name?: string | null
          adset_id?: string | null
          attempts?: number
          campaign_id?: string | null
          campaign_name?: string | null
          company_id?: string
          created_at?: string
          error?: string | null
          form_id?: string | null
          form_name?: string | null
          id?: string
          lead_id?: string | null
          leadgen_id?: string
          state?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "meta_lead_events_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "meta_lead_events_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      meta_lead_routing: {
        Row: {
          company_id: string
          last_assigned_at: string | null
          user_id: string
        }
        Insert: {
          company_id: string
          last_assigned_at?: string | null
          user_id: string
        }
        Update: {
          company_id?: string
          last_assigned_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "meta_lead_routing_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "meta_lead_routing_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      niches: {
        Row: {
          archived_at: string | null
          company_id: string
          created_at: string
          created_by: string | null
          id: string
          merged_into_id: string | null
          name: string
          normalized_name: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          company_id?: string
          created_at?: string
          created_by?: string | null
          id?: string
          merged_into_id?: string | null
          name: string
          normalized_name?: never
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          company_id?: string
          created_at?: string
          created_by?: string | null
          id?: string
          merged_into_id?: string | null
          name?: string
          normalized_name?: never
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "niches_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "niches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "niches_merged_into_id_fkey"
            columns: ["merged_into_id"]
            isOneToOne: false
            referencedRelation: "niches"
            referencedColumns: ["id"]
          },
        ]
      }
      notification_settings: {
        Row: {
          disabled_kinds: string[]
          updated_at: string
          user_id: string
        }
        Insert: {
          disabled_kinds?: string[]
          updated_at?: string
          user_id: string
        }
        Update: {
          disabled_kinds?: string[]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notification_settings_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      pipeline_stages: {
        Row: {
          archived_at: string | null
          color: string
          company_id: string
          created_at: string
          id: string
          kind: Database["public"]["Enums"]["lead_outcome"]
          name: string
          position: number
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          color?: string
          company_id: string
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["lead_outcome"]
          name: string
          position: number
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          color?: string
          company_id?: string
          created_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["lead_outcome"]
          name?: string
          position?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "pipeline_stages_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          active_company_id: string | null
          ads_client_id: string | null
          company_id: string | null
          created_at: string
          display_name: string
          id: string
          is_active: boolean
          role: Database["public"]["Enums"]["app_role"]
          updated_at: string
          username: string
        }
        Insert: {
          active_company_id?: string | null
          ads_client_id?: string | null
          company_id?: string | null
          created_at?: string
          display_name: string
          id: string
          is_active?: boolean
          role: Database["public"]["Enums"]["app_role"]
          updated_at?: string
          username: string
        }
        Update: {
          active_company_id?: string | null
          ads_client_id?: string | null
          company_id?: string | null
          created_at?: string
          display_name?: string
          id?: string
          is_active?: boolean
          role?: Database["public"]["Enums"]["app_role"]
          updated_at?: string
          username?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_active_company_id_fkey"
            columns: ["active_company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_ads_client_id_fkey"
            columns: ["ads_client_id"]
            isOneToOne: false
            referencedRelation: "ads_clients"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
        ]
      }
      reminder_deliveries: {
        Row: {
          attempts: number
          created_at: string
          due_at: string
          follow_up_id: string
          id: string
          kind: string
          last_error: string | null
          lease_token: string | null
          next_attempt_at: string
          recipient_id: string
          revision: number
          sent_at: string | null
          state: Database["public"]["Enums"]["reminder_state"]
          telegram_message_id: number | null
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          due_at: string
          follow_up_id: string
          id?: string
          kind?: string
          last_error?: string | null
          lease_token?: string | null
          next_attempt_at: string
          recipient_id: string
          revision: number
          sent_at?: string | null
          state?: Database["public"]["Enums"]["reminder_state"]
          telegram_message_id?: number | null
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          due_at?: string
          follow_up_id?: string
          id?: string
          kind?: string
          last_error?: string | null
          lease_token?: string | null
          next_attempt_at?: string
          recipient_id?: string
          revision?: number
          sent_at?: string | null
          state?: Database["public"]["Enums"]["reminder_state"]
          telegram_message_id?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reminder_deliveries_follow_up_id_fkey"
            columns: ["follow_up_id"]
            isOneToOne: false
            referencedRelation: "follow_ups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reminder_deliveries_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      share_events: {
        Row: {
          actor_id: string | null
          created_at: string
          device: string | null
          file_id: string | null
          file_name: string | null
          id: string
          lead_id: string
          meta: Json
          share_id: string
          type: Database["public"]["Enums"]["share_event_type"]
        }
        Insert: {
          actor_id?: string | null
          created_at?: string
          device?: string | null
          file_id?: string | null
          file_name?: string | null
          id?: string
          lead_id: string
          meta?: Json
          share_id: string
          type: Database["public"]["Enums"]["share_event_type"]
        }
        Update: {
          actor_id?: string | null
          created_at?: string
          device?: string | null
          file_id?: string | null
          file_name?: string | null
          id?: string
          lead_id?: string
          meta?: Json
          share_id?: string
          type?: Database["public"]["Enums"]["share_event_type"]
        }
        Relationships: [
          {
            foreignKeyName: "share_events_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "share_events_file_id_fkey"
            columns: ["file_id"]
            isOneToOne: false
            referencedRelation: "library_files"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "share_events_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "share_events_share_id_fkey"
            columns: ["share_id"]
            isOneToOne: false
            referencedRelation: "lead_shares"
            referencedColumns: ["id"]
          },
        ]
      }
      telegram_connections: {
        Row: {
          chat_id: number
          connected_at: string
          last_error: string | null
          status: Database["public"]["Enums"]["telegram_status"]
          telegram_username: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          chat_id: number
          connected_at?: string
          last_error?: string | null
          status?: Database["public"]["Enums"]["telegram_status"]
          telegram_username?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          chat_id?: number
          connected_at?: string
          last_error?: string | null
          status?: Database["public"]["Enums"]["telegram_status"]
          telegram_username?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "telegram_connections_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      telegram_link_tokens: {
        Row: {
          consumed_at: string | null
          created_at: string
          expires_at: string
          token_hash: string
          user_id: string
        }
        Insert: {
          consumed_at?: string | null
          created_at?: string
          expires_at: string
          token_hash: string
          user_id: string
        }
        Update: {
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          token_hash?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "telegram_link_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      telegram_notifications: {
        Row: {
          attempts: number
          created_at: string
          dedupe_key: string
          follow_up_id: string | null
          id: string
          kind: string
          last_error: string | null
          lead_id: string | null
          lease_token: string | null
          next_attempt_at: string
          payload: Json
          recipient_id: string
          sent_at: string | null
          state: Database["public"]["Enums"]["reminder_state"]
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          dedupe_key: string
          follow_up_id?: string | null
          id?: string
          kind: string
          last_error?: string | null
          lead_id?: string | null
          lease_token?: string | null
          next_attempt_at?: string
          payload: Json
          recipient_id: string
          sent_at?: string | null
          state?: Database["public"]["Enums"]["reminder_state"]
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          dedupe_key?: string
          follow_up_id?: string | null
          id?: string
          kind?: string
          last_error?: string | null
          lead_id?: string | null
          lease_token?: string | null
          next_attempt_at?: string
          payload?: Json
          recipient_id?: string
          sent_at?: string | null
          state?: Database["public"]["Enums"]["reminder_state"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "telegram_notifications_follow_up_id_fkey"
            columns: ["follow_up_id"]
            isOneToOne: false
            referencedRelation: "follow_ups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "telegram_notifications_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "telegram_notifications_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      ad_account_detail: {
        Args: {
          p_account: string
        }
        Returns: Json
      }
      ad_account_secrets: {
        Args: {
          p_account: string
        }
        Returns: {
          id: string
          act_id: string
          app_id: string
          app_secret: string
          access_token: string
          timezone: string
          synced_through: string
          backfilled_from: string
          created_at: string
        }[]
      }
      ad_campaign_detail: {
        Args: {
          p_campaign: string
          p_from: string
          p_to: string
        }
        Returns: Json
      }
      ad_categories_list: {
        Args: {
          p_account: string
        }
        Returns: Json
      }
      ad_sync_targets: {
        Args: {
          p_limit?: number
        }
        Returns: string[]
      }
      admin_list_users: {
        Args: {
          p_search?: string
          p_role?: Database["public"]["Enums"]["app_role"]
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      admin_log_password_reset: {
        Args: {
          p_user_id: string
        }
        Returns: undefined
      }
      admin_purge_library_file: {
        Args: {
          p_file_id: string
        }
        Returns: undefined
      }
      admin_unregistered_uploads: {
        Args: {
          p_limit?: number
        }
        Returns: Json
      }
      admin_update_user: {
        Args: {
          p_user_id: string
          p_display_name?: string
          p_role?: Database["public"]["Enums"]["app_role"]
          p_is_active?: boolean
        }
        Returns: Database["public"]["Tables"]["profiles"]["Row"]
      }
      admin_usage: {
        Args: never
        Returns: Json
      }
      ads_accounts_for_me: {
        Args: never
        Returns: Json
      }
      ads_client_detail: {
        Args: {
          p_id: string
        }
        Returns: Json
      }
      ads_client_login_check: {
        Args: {
          p_client: string
        }
        Returns: string
      }
      ads_overview: {
        Args: {
          p_account: string
          p_from: string
          p_to: string
          p_category?: string
          p_uncategorised?: boolean
        }
        Returns: Json
      }
      archive_ad_category: {
        Args: {
          p_id: string
        }
        Returns: undefined
      }
      archive_pipeline_stage: {
        Args: {
          p_id: string
          p_move_to?: string
        }
        Returns: number
      }
      check_duplicate_phone: {
        Args: {
          p_phone_normalized: string
          p_exclude_lead_id?: string
        }
        Returns: Json
      }
      claim_due_notifications: {
        Args: {
          p_limit?: number
          p_lease_seconds?: number
        }
        Returns: {
          notification_id: string
          lease_token: string
          chat_id: number
          kind: string
          payload: Json
          attempts: number
        }[]
      }
      claim_due_reminders: {
        Args: {
          p_limit?: number
          p_lease_seconds?: number
        }
        Returns: {
          delivery_id: string
          lease_token: string
          chat_id: number
          lead_id: string
          lead_name: string
          lead_phone: string
          task: string
          due_at: string
          attempts: number
        }[]
      }
      complete_follow_up: {
        Args: {
          p_id: string
          p_outcome?: string
          p_next_due_at?: string
          p_next_task?: string
        }
        Returns: string
      }
      consume_telegram_link_token: {
        Args: {
          p_token: string
          p_chat_id: number
          p_telegram_username?: string
        }
        Returns: Json
      }
      correct_note: {
        Args: {
          p_note_id: string
          p_body: string
        }
        Returns: undefined
      }
      create_ads_client: {
        Args: {
          p_name: string
          p_phone?: string
          p_email?: string
          p_business?: string
          p_notes?: string
        }
        Returns: string
      }
      create_company: {
        Args: {
          p_name: string
          p_brand_highlight?: string
        }
        Returns: string
      }
      create_lead: {
        Args: {
          p_name: string
          p_phone: string
          p_phone_normalized: string
          p_email?: string
          p_niche_id?: string
          p_new_niche?: string
          p_stage_id?: string
          p_owner_id?: string
          p_note?: string
          p_follow_up_at?: string
          p_follow_up_task?: string
          p_allow_duplicate?: boolean
        }
        Returns: string
      }
      create_telegram_link_token: {
        Args: never
        Returns: string
      }
      dashboard_admin: {
        Args: {
          p_days?: number
          p_from?: string
          p_to?: string
        }
        Returns: Json
      }
      dashboard_finance: {
        Args: {
          p_months?: number
        }
        Returns: Json
      }
      dashboard_sales: {
        Args: {
          p_days?: number
          p_from?: string
          p_to?: string
        }
        Returns: Json
      }
      delete_meta_integration: {
        Args: {
          p_company_id: string
        }
        Returns: undefined
      }
      disconnect_ad_account: {
        Args: {
          p_account: string
        }
        Returns: undefined
      }
      disconnect_telegram: {
        Args: never
        Returns: undefined
      }
      fail_meta_lead: {
        Args: {
          p_company_id: string
          p_leadgen_id: string
          p_error: string
        }
        Returns: undefined
      }
      finance_company_split: {
        Args: {
          p_from: string
          p_to: string
        }
        Returns: Json
      }
      finance_context: {
        Args: never
        Returns: Json
      }
      finance_period_report: {
        Args: {
          p_from: string
          p_to: string
        }
        Returns: Json
      }
      finance_year_overview: {
        Args: {
          p_year: number
        }
        Returns: Json
      }
      finish_notification: {
        Args: {
          p_id: string
          p_lease_token: string
          p_result: string
          p_error?: string
          p_retry_after_seconds?: number
        }
        Returns: string
      }
      finish_reminder: {
        Args: {
          p_delivery_id: string
          p_lease_token: string
          p_result: string
          p_error?: string
          p_retry_after_seconds?: number
          p_message_id?: number
        }
        Returns: string
      }
      ingest_meta_lead: {
        Args: {
          p_company_id: string
          p_leadgen_id: string
          p_name: string
          p_phone: string
          p_phone_normalized: string
          p_email?: string
          p_form_id?: string
          p_form_name?: string
          p_ad_name?: string
          p_campaign_name?: string
          p_answers?: string
        }
        Returns: Json
      }
      lead_share_summary: {
        Args: {
          p_lead_id: string
        }
        Returns: Json
      }
      library_folder_options: {
        Args: never
        Returns: Json
      }
      library_folder_path: {
        Args: {
          p_folder_id: string
        }
        Returns: Json
      }
      list_ad_campaigns: {
        Args: {
          p_account: string
          p_from: string
          p_to: string
          p_category?: string
          p_uncategorised?: boolean
          p_search?: string
          p_status?: string
          p_sort?: string
          p_dir?: string
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      list_ads_clients: {
        Args: {
          p_search?: string
          p_status?: string
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      list_finance_entries: {
        Args: {
          p_kind: string
          p_from: string
          p_to: string
          p_search?: string
          p_category_id?: string
          p_mode?: string
          p_recurring?: boolean
          p_archived?: boolean
          p_sort?: string
          p_dir?: string
          p_limit?: number
          p_offset?: number
          p_company_id?: string
        }
        Returns: Json
      }
      list_follow_ups: {
        Args: {
          p_view?: string
          p_assignee_id?: string
          p_search?: string
          p_limit?: number
          p_offset?: number
          p_due_from?: string
          p_due_to?: string
        }
        Returns: Json
      }
      list_leads: {
        Args: {
          p_search?: string
          p_stage_ids?: string[]
          p_niche_id?: string
          p_owner_id?: string
          p_created_from?: string
          p_created_to?: string
          p_overdue_only?: boolean
          p_archived?: boolean
          p_sort?: string
          p_dir?: string
          p_limit?: number
          p_offset?: number
          p_starred_only?: boolean
        }
        Returns: Json
      }
      list_library_items: {
        Args: {
          p_parent_id?: string
          p_search?: string
          p_archived?: boolean
          p_sort?: string
          p_dir?: string
          p_folders_first?: boolean
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      log_call: {
        Args: {
          p_lead_id: string
        }
        Returns: string
      }
      merge_ad_account: {
        Args: {
          p_account: string
          p_company_ids: string[]
        }
        Returns: undefined
      }
      merge_finance: {
        Args: {
          p_company_ids: string[]
          p_editor_ids: string[]
        }
        Returns: string
      }
      merge_niches: {
        Args: {
          p_source_id: string
          p_target_id: string
        }
        Returns: number
      }
      meta_integration_secrets: {
        Args: {
          p_company_id: string
        }
        Returns: {
          app_id: string
          page_id: string
          verify_token: string
          app_secret: string
          access_token: string
        }[]
      }
      meta_lead_insights: {
        Args: {
          p_company_id: string
          p_from: string
          p_to: string
        }
        Returns: Json
      }
      move_library_items: {
        Args: {
          p_target_folder_id: string
          p_items: Json
        }
        Returns: number
      }
      my_portal: {
        Args: never
        Returns: Json
      }
      open_lead_share: {
        Args: {
          p_token: string
          p_count_view?: boolean
          p_device?: string
        }
        Returns: Json
      }
      record_meta_leadgen: {
        Args: {
          p_company_id: string
          p_leadgen_id: string
          p_form_id?: string
        }
        Returns: boolean
      }
      remove_share_file: {
        Args: {
          p_share_id: string
          p_file_id: string
        }
        Returns: undefined
      }
      reorder_library_items: {
        Args: {
          p_parent_id: string
          p_items: Json
        }
        Returns: undefined
      }
      reorder_pipeline_stages: {
        Args: {
          p_ids: string[]
        }
        Returns: undefined
      }
      report_finance: {
        Args: {
          p_from: string
          p_to: string
        }
        Returns: Json
      }
      report_leads: {
        Args: {
          p_from: string
          p_to: string
        }
        Returns: Json
      }
      resolve_expense_category: {
        Args: {
          p_id?: string
          p_new_name?: string
        }
        Returns: string
      }
      resolve_share_file: {
        Args: {
          p_token: string
          p_file_id: string
        }
        Returns: Json
      }
      revoke_lead_share: {
        Args: {
          p_share_id: string
        }
        Returns: undefined
      }
      save_ad_account: {
        Args: {
          p_kind: string
          p_owner: string
          p_act_id: string
          p_app_id?: string
          p_app_secret?: string
          p_access_token?: string
          p_use_lead_app?: boolean
        }
        Returns: string
      }
      save_ad_category: {
        Args: {
          p_account: string
          p_id: string
          p_name: string
          p_match_text?: string
        }
        Returns: string
      }
      save_meta_integration: {
        Args: {
          p_company_id: string
          p_app_id: string
          p_page_id: string
          p_app_secret?: string
          p_access_token?: string
        }
        Returns: undefined
      }
      save_pipeline_stage: {
        Args: {
          p_id: string
          p_name: string
          p_kind: Database["public"]["Enums"]["lead_outcome"]
          p_color: string
        }
        Returns: string
      }
      send_test_notification: {
        Args: never
        Returns: undefined
      }
      set_active_company: {
        Args: {
          p_company_id: string
        }
        Returns: undefined
      }
      set_ad_account_state: {
        Args: {
          p_account: string
          p_status: string
          p_error?: string
          p_name?: string
          p_currency?: string
          p_timezone?: string
          p_synced_through?: string
          p_backfilled_from?: string
          p_next_sync_after?: string
          p_synced?: boolean
        }
        Returns: undefined
      }
      set_ad_campaign_category: {
        Args: {
          p_campaign_ids: string[]
          p_category_id: string
        }
        Returns: number
      }
      set_ads_client_status: {
        Args: {
          p_id: string
          p_status: string
          p_disable_logins?: boolean
        }
        Returns: undefined
      }
      set_ads_manager_companies: {
        Args: {
          p_user_id: string
          p_company_ids: string[]
        }
        Returns: undefined
      }
      set_call_outcome: {
        Args: {
          p_activity_id: string
          p_outcome: string
          p_note?: string
        }
        Returns: undefined
      }
      set_client_login: {
        Args: {
          p_user_id: string
          p_is_active?: boolean
          p_password_reset?: boolean
        }
        Returns: undefined
      }
      set_expense_recurrence: {
        Args: {
          p_expense_id: string
          p_repeat: boolean
        }
        Returns: string
      }
      set_finance_editors: {
        Args: {
          p_company_ids: string[]
        }
        Returns: undefined
      }
      set_follow_up_pin: {
        Args: {
          p_follow_up_id: string
          p_pinned: boolean
        }
        Returns: Json
      }
      set_follow_up_star: {
        Args: {
          p_follow_up_id: string
          p_starred: boolean
        }
        Returns: Json
      }
      set_lead_pin: {
        Args: {
          p_lead_id: string
          p_pinned: boolean
        }
        Returns: Json
      }
      set_lead_star: {
        Args: {
          p_lead_id: string
          p_starred: boolean
        }
        Returns: Json
      }
      set_library_thumbnail: {
        Args: {
          p_file_id: string
          p_path: string
        }
        Returns: undefined
      }
      set_meta_lead_ad_ids: {
        Args: {
          p_company_id: string
          p_leadgen_id: string
          p_campaign_id: string
          p_adset_id: string
          p_ad_id: string
        }
        Returns: undefined
      }
      set_meta_routing: {
        Args: {
          p_company_id: string
          p_user_ids: string[]
        }
        Returns: undefined
      }
      set_meta_status: {
        Args: {
          p_company_id: string
          p_status: string
          p_page_name?: string
          p_error?: string
        }
        Returns: undefined
      }
      set_notification_pref: {
        Args: {
          p_kind: string
          p_enabled: boolean
        }
        Returns: string[]
      }
      set_won_to_ads_client: {
        Args: {
          p_company_id: string
          p_enabled: boolean
        }
        Returns: undefined
      }
      share_brand: {
        Args: {
          p_token: string
        }
        Returns: Json
      }
      share_lead_files: {
        Args: {
          p_lead_id: string
          p_file_ids: string[]
          p_expiry: string
        }
        Returns: Json
      }
      silence_follow_up_nag: {
        Args: {
          p_chat_id: number
          p_follow_up_id: string
        }
        Returns: Json
      }
      split_finance: {
        Args: {
          p_company_id: string
        }
        Returns: undefined
      }
      super_ads_overview: {
        Args: never
        Returns: Json
      }
      super_finance_groups: {
        Args: never
        Returns: Json
      }
      super_lead_company: {
        Args: {
          p_lead_id: string
        }
        Returns: string
      }
      super_list_ads_managers: {
        Args: never
        Returns: Json
      }
      super_list_companies: {
        Args: never
        Returns: Json
      }
      super_meta_events: {
        Args: {
          p_company_id: string
          p_limit?: number
        }
        Returns: Json
      }
      super_meta_overview: {
        Args: never
        Returns: Json
      }
      super_update_ads_manager: {
        Args: {
          p_user_id: string
          p_display_name?: string
          p_is_active?: boolean
          p_password_reset?: boolean
        }
        Returns: undefined
      }
      track_share_file: {
        Args: {
          p_token: string
          p_file_id: string
          p_kind: string
          p_device?: string
        }
        Returns: Json
      }
      update_ads_client: {
        Args: {
          p_id: string
          p_name?: string
          p_phone?: string
          p_email?: string
          p_business?: string
          p_notes?: string
        }
        Returns: undefined
      }
      update_company: {
        Args: {
          p_company_id: string
          p_name?: string
          p_brand_highlight?: string
          p_logo_path?: string
          p_clear_logo?: boolean
        }
        Returns: undefined
      }
      update_expense_category: {
        Args: {
          p_id: string
          p_name?: string
          p_archived?: boolean
        }
        Returns: undefined
      }
      update_lead: {
        Args: {
          p_id: string
          p_version: number
          p_name: string
          p_phone: string
          p_phone_normalized: string
          p_email?: string
          p_niche_id?: string
          p_new_niche?: string
          p_allow_duplicate?: boolean
        }
        Returns: number
      }
      upsert_ad_entities: {
        Args: {
          p_account: string
          p_campaigns: Json
          p_ads: Json
        }
        Returns: undefined
      }
      upsert_ad_insights: {
        Args: {
          p_account: string
          p_level: string
          p_rows: Json
        }
        Returns: number
      }
      upsert_ad_reach: {
        Args: {
          p_account: string
          p_rows: Json
        }
        Returns: undefined
      }
    }
    Enums: {
      app_role: "admin" | "sales" | "account" | "super_admin" | "ads_manager" | "client"
      follow_up_state: "pending" | "completed" | "cancelled"
      lead_activity_type: "lead_created" | "note" | "note_corrected" | "status_changed" | "assigned" | "lead_updated" | "lead_archived" | "lead_restored" | "follow_up_scheduled" | "follow_up_rescheduled" | "follow_up_updated" | "follow_up_completed" | "follow_up_cancelled" | "call_logged" | "files_shared" | "share_revoked" | "share_opened"
      lead_outcome: "open" | "won" | "lost"
      reminder_state: "pending" | "processing" | "sent" | "failed" | "skipped" | "cancelled"
      share_event_type: "link_created" | "files_added" | "file_removed" | "opened" | "file_viewed" | "file_downloaded" | "expiry_changed" | "revoked"
      telegram_status: "connected" | "blocked"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database["public"]
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]

export const Constants = {
  public: {
    Enums: {
      app_role: ["admin", "sales", "account", "super_admin", "ads_manager", "client"],
      follow_up_state: ["pending", "completed", "cancelled"],
      lead_activity_type: ["lead_created", "note", "note_corrected", "status_changed", "assigned", "lead_updated", "lead_archived", "lead_restored", "follow_up_scheduled", "follow_up_rescheduled", "follow_up_updated", "follow_up_completed", "follow_up_cancelled", "call_logged", "files_shared", "share_revoked", "share_opened"],
      lead_outcome: ["open", "won", "lost"],
      reminder_state: ["pending", "processing", "sent", "failed", "skipped", "cancelled"],
      share_event_type: ["link_created", "files_added", "file_removed", "opened", "file_viewed", "file_downloaded", "expiry_changed", "revoked"],
      telegram_status: ["connected", "blocked"],
    },
  },
} as const
