// Generated by scripts/gen-db-types.mjs from supabase/migrations. Do not edit by hand.
// Regenerate with: pnpm db:types (local) or pnpm db:types:remote (linked Supabase project).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "13" }
  public: {
    Tables: {
      admin_audit_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          meta: Json
          target_user_id: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          meta?: Json
          target_user_id?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          meta?: Json
          target_user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "admin_audit_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "admin_audit_log_target_user_id_fkey"
            columns: ["target_user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      capital_entries: {
        Row: {
          amount: number
          archived_at: string | null
          archived_by: string | null
          contributor: string
          created_at: string
          created_by: string
          description: string | null
          entry_date: string
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          amount: number
          archived_at?: string | null
          archived_by?: string | null
          contributor: string
          created_at?: string
          created_by: string
          description?: string | null
          entry_date: string
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          amount?: number
          archived_at?: string | null
          archived_by?: string | null
          contributor?: string
          created_at?: string
          created_by?: string
          description?: string | null
          entry_date?: string
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "capital_entries_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "capital_entries_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "capital_entries_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      expenses: {
        Row: {
          amount: number
          archived_at: string | null
          archived_by: string | null
          category: Database["public"]["Enums"]["expense_category"]
          created_at: string
          created_by: string
          description: string | null
          expense_date: string
          id: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          amount: number
          archived_at?: string | null
          archived_by?: string | null
          category: Database["public"]["Enums"]["expense_category"]
          created_at?: string
          created_by: string
          description?: string | null
          expense_date: string
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          amount?: number
          archived_at?: string | null
          archived_by?: string | null
          category?: Database["public"]["Enums"]["expense_category"]
          created_at?: string
          created_by?: string
          description?: string | null
          expense_date?: string
          id?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "expenses_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "expenses_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      finance_activities: {
        Row: {
          action: string
          actor_id: string | null
          changes: Json
          created_at: string
          entity_id: string
          entity_type: string
          id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          changes?: Json
          created_at?: string
          entity_id: string
          entity_type: string
          id?: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          changes?: Json
          created_at?: string
          entity_id?: string
          entity_type?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "finance_activities_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      follow_ups: {
        Row: {
          assignee_id: string
          cancelled_at: string | null
          completed_at: string | null
          completed_by: string | null
          created_at: string
          created_by: string
          due_at: string
          id: string
          lead_id: string
          outcome: string | null
          revision: number
          state: Database["public"]["Enums"]["follow_up_state"]
          task: string
          updated_at: string
        }
        Insert: {
          assignee_id: string
          cancelled_at?: string | null
          completed_at?: string | null
          completed_by?: string | null
          created_at?: string
          created_by: string
          due_at: string
          id?: string
          lead_id: string
          outcome?: string | null
          revision?: number
          state?: Database["public"]["Enums"]["follow_up_state"]
          task: string
          updated_at?: string
        }
        Update: {
          assignee_id?: string
          cancelled_at?: string | null
          completed_at?: string | null
          completed_by?: string | null
          created_at?: string
          created_by?: string
          due_at?: string
          id?: string
          lead_id?: string
          outcome?: string | null
          revision?: number
          state?: Database["public"]["Enums"]["follow_up_state"]
          task?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "follow_ups_assignee_id_fkey"
            columns: ["assignee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_ups_completed_by_fkey"
            columns: ["completed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_ups_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follow_ups_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_activities: {
        Row: {
          actor_id: string | null
          body: string | null
          created_at: string
          edited_at: string | null
          follow_up_id: string | null
          id: string
          lead_id: string
          meta: Json
          type: Database["public"]["Enums"]["lead_activity_type"]
        }
        Insert: {
          actor_id?: string | null
          body?: string | null
          created_at?: string
          edited_at?: string | null
          follow_up_id?: string | null
          id?: string
          lead_id: string
          meta?: Json
          type: Database["public"]["Enums"]["lead_activity_type"]
        }
        Update: {
          actor_id?: string | null
          body?: string | null
          created_at?: string
          edited_at?: string | null
          follow_up_id?: string | null
          id?: string
          lead_id?: string
          meta?: Json
          type?: Database["public"]["Enums"]["lead_activity_type"]
        }
        Relationships: [
          {
            foreignKeyName: "lead_activities_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_activities_follow_up_id_fkey"
            columns: ["follow_up_id"]
            isOneToOne: false
            referencedRelation: "follow_ups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_activities_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          archived_at: string | null
          archived_by: string | null
          created_at: string
          created_by: string
          email: string | null
          id: string
          name: string
          niche_id: string
          owner_id: string
          phone: string
          phone_normalized: string
          status: Database["public"]["Enums"]["lead_status"]
          updated_at: string
          version: number
        }
        Insert: {
          archived_at?: string | null
          archived_by?: string | null
          created_at?: string
          created_by: string
          email?: string | null
          id?: string
          name: string
          niche_id: string
          owner_id: string
          phone: string
          phone_normalized: string
          status?: Database["public"]["Enums"]["lead_status"]
          updated_at?: string
          version?: number
        }
        Update: {
          archived_at?: string | null
          archived_by?: string | null
          created_at?: string
          created_by?: string
          email?: string | null
          id?: string
          name?: string
          niche_id?: string
          owner_id?: string
          phone?: string
          phone_normalized?: string
          status?: Database["public"]["Enums"]["lead_status"]
          updated_at?: string
          version?: number
        }
        Relationships: [
          {
            foreignKeyName: "leads_archived_by_fkey"
            columns: ["archived_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_niche_id_fkey"
            columns: ["niche_id"]
            isOneToOne: false
            referencedRelation: "niches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "leads_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      niches: {
        Row: {
          archived_at: string | null
          created_at: string
          created_by: string | null
          id: string
          merged_into_id: string | null
          name: string
          normalized_name: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          merged_into_id?: string | null
          name: string
          normalized_name?: never
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          created_by?: string | null
          id?: string
          merged_into_id?: string | null
          name?: string
          normalized_name?: never
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "niches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "niches_merged_into_id_fkey"
            columns: ["merged_into_id"]
            isOneToOne: false
            referencedRelation: "niches"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string
          id: string
          is_active: boolean
          role: Database["public"]["Enums"]["app_role"]
          updated_at: string
          username: string
        }
        Insert: {
          created_at?: string
          display_name: string
          id: string
          is_active?: boolean
          role: Database["public"]["Enums"]["app_role"]
          updated_at?: string
          username: string
        }
        Update: {
          created_at?: string
          display_name?: string
          id?: string
          is_active?: boolean
          role?: Database["public"]["Enums"]["app_role"]
          updated_at?: string
          username?: string
        }
        Relationships: []
      }
      reminder_deliveries: {
        Row: {
          attempts: number
          created_at: string
          due_at: string
          follow_up_id: string
          id: string
          kind: string
          last_error: string | null
          lease_token: string | null
          next_attempt_at: string
          recipient_id: string
          revision: number
          sent_at: string | null
          state: Database["public"]["Enums"]["reminder_state"]
          telegram_message_id: number | null
          updated_at: string
        }
        Insert: {
          attempts?: number
          created_at?: string
          due_at: string
          follow_up_id: string
          id?: string
          kind?: string
          last_error?: string | null
          lease_token?: string | null
          next_attempt_at: string
          recipient_id: string
          revision: number
          sent_at?: string | null
          state?: Database["public"]["Enums"]["reminder_state"]
          telegram_message_id?: number | null
          updated_at?: string
        }
        Update: {
          attempts?: number
          created_at?: string
          due_at?: string
          follow_up_id?: string
          id?: string
          kind?: string
          last_error?: string | null
          lease_token?: string | null
          next_attempt_at?: string
          recipient_id?: string
          revision?: number
          sent_at?: string | null
          state?: Database["public"]["Enums"]["reminder_state"]
          telegram_message_id?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reminder_deliveries_follow_up_id_fkey"
            columns: ["follow_up_id"]
            isOneToOne: false
            referencedRelation: "follow_ups"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reminder_deliveries_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      telegram_connections: {
        Row: {
          chat_id: number
          connected_at: string
          last_error: string | null
          status: Database["public"]["Enums"]["telegram_status"]
          telegram_username: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          chat_id: number
          connected_at?: string
          last_error?: string | null
          status?: Database["public"]["Enums"]["telegram_status"]
          telegram_username?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          chat_id?: number
          connected_at?: string
          last_error?: string | null
          status?: Database["public"]["Enums"]["telegram_status"]
          telegram_username?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "telegram_connections_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      telegram_link_tokens: {
        Row: {
          consumed_at: string | null
          created_at: string
          expires_at: string
          token_hash: string
          user_id: string
        }
        Insert: {
          consumed_at?: string | null
          created_at?: string
          expires_at: string
          token_hash: string
          user_id: string
        }
        Update: {
          consumed_at?: string | null
          created_at?: string
          expires_at?: string
          token_hash?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "telegram_link_tokens_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: { [_ in never]: never }
    Functions: {
      admin_list_users: {
        Args: {
          p_search?: string
          p_role?: Database["public"]["Enums"]["app_role"]
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      admin_log_password_reset: {
        Args: {
          p_user_id: string
        }
        Returns: undefined
      }
      admin_update_user: {
        Args: {
          p_user_id: string
          p_display_name?: string
          p_role?: Database["public"]["Enums"]["app_role"]
          p_is_active?: boolean
        }
        Returns: Database["public"]["Tables"]["profiles"]["Row"]
      }
      check_duplicate_phone: {
        Args: {
          p_phone_normalized: string
          p_exclude_lead_id?: string
        }
        Returns: Json
      }
      claim_due_reminders: {
        Args: {
          p_limit?: number
          p_lease_seconds?: number
        }
        Returns: {
          delivery_id: string
          lease_token: string
          chat_id: number
          lead_id: string
          lead_name: string
          lead_phone: string
          task: string
          due_at: string
          attempts: number
        }[]
      }
      complete_follow_up: {
        Args: {
          p_id: string
          p_outcome?: string
          p_next_due_at?: string
          p_next_task?: string
        }
        Returns: string
      }
      consume_telegram_link_token: {
        Args: {
          p_token: string
          p_chat_id: number
          p_telegram_username?: string
        }
        Returns: Json
      }
      correct_note: {
        Args: {
          p_note_id: string
          p_body: string
        }
        Returns: undefined
      }
      create_lead: {
        Args: {
          p_name: string
          p_phone: string
          p_phone_normalized: string
          p_email?: string
          p_niche_id?: string
          p_new_niche?: string
          p_status?: Database["public"]["Enums"]["lead_status"]
          p_owner_id?: string
          p_note?: string
          p_follow_up_at?: string
          p_follow_up_task?: string
          p_allow_duplicate?: boolean
        }
        Returns: string
      }
      create_telegram_link_token: {
        Args: never
        Returns: string
      }
      dashboard_admin: {
        Args: {
          p_days?: number
        }
        Returns: Json
      }
      dashboard_finance: {
        Args: {
          p_months?: number
        }
        Returns: Json
      }
      dashboard_sales: {
        Args: {
          p_days?: number
        }
        Returns: Json
      }
      disconnect_telegram: {
        Args: never
        Returns: undefined
      }
      finish_reminder: {
        Args: {
          p_delivery_id: string
          p_lease_token: string
          p_result: string
          p_error?: string
          p_retry_after_seconds?: number
          p_message_id?: number
        }
        Returns: string
      }
      list_follow_ups: {
        Args: {
          p_view?: string
          p_assignee_id?: string
          p_search?: string
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      list_leads: {
        Args: {
          p_search?: string
          p_statuses?: Database["public"]["Enums"]["lead_status"][]
          p_niche_id?: string
          p_owner_id?: string
          p_created_from?: string
          p_created_to?: string
          p_overdue_only?: boolean
          p_archived?: boolean
          p_sort?: string
          p_dir?: string
          p_limit?: number
          p_offset?: number
        }
        Returns: Json
      }
      merge_niches: {
        Args: {
          p_source_id: string
          p_target_id: string
        }
        Returns: number
      }
      update_lead: {
        Args: {
          p_id: string
          p_version: number
          p_name: string
          p_phone: string
          p_phone_normalized: string
          p_email?: string
          p_niche_id?: string
          p_new_niche?: string
          p_allow_duplicate?: boolean
        }
        Returns: number
      }
    }
    Enums: {
      app_role: "admin" | "sales" | "account"
      expense_category: "salary" | "rent" | "software" | "marketing" | "utilities" | "miscellaneous"
      follow_up_state: "pending" | "completed" | "cancelled"
      lead_activity_type: "lead_created" | "note" | "note_corrected" | "status_changed" | "assigned" | "lead_updated" | "lead_archived" | "lead_restored" | "follow_up_scheduled" | "follow_up_rescheduled" | "follow_up_updated" | "follow_up_completed" | "follow_up_cancelled"
      lead_status: "new" | "contacted" | "interested" | "proposal_sent" | "won" | "lost"
      reminder_state: "pending" | "processing" | "sent" | "failed" | "skipped" | "cancelled"
      telegram_status: "connected" | "blocked"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

type PublicSchema = Database["public"]
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]

export const Constants = {
  public: {
    Enums: {
      app_role: ["admin", "sales", "account"],
      expense_category: ["salary", "rent", "software", "marketing", "utilities", "miscellaneous"],
      follow_up_state: ["pending", "completed", "cancelled"],
      lead_activity_type: ["lead_created", "note", "note_corrected", "status_changed", "assigned", "lead_updated", "lead_archived", "lead_restored", "follow_up_scheduled", "follow_up_rescheduled", "follow_up_updated", "follow_up_completed", "follow_up_cancelled"],
      lead_status: ["new", "contacted", "interested", "proposal_sent", "won", "lost"],
      reminder_state: ["pending", "processing", "sent", "failed", "skipped", "cancelled"],
      telegram_status: ["connected", "blocked"],
    },
  },
} as const
